### ISSUE TITLE
Let me know if you want Actions

### ISSUE THREAD

**Issue by bdougie** [bdougie/_delete#2]
https://github.com/features/actions

**Comment by jdecked** [comment]
I'd love actions access :-) (already registered for the beta waitlist of course)

**Comment by jasonbarry** [comment]
@jasonbarry 👋 I've signed up for the beta

**Comment by doodla** [comment]
I'd like Actions access. ( signed up for the beta )

**Comment by jasonbarry** [comment]
Also if you could add @eric-silverman plz

**Comment by lianthompson** [comment]
already signed up!

**Comment by moomou** [comment]
actions please!

**Comment by chloewlin** [comment]
Hi, please sign me up for the beta. Thank you!

**Comment by jigyasa-grover** [comment]
We'd want it !
@jigyasa-grover
@Casey

Thanks for the workshop 🥳

**Comment by mmedina3** [comment]
Signed up, thanks!

**Comment by jordanblum1** [comment]
@jordanblum1 access to actions beta please.

thanks for the workshop!

**Comment by Sherri010** [comment]
love to have  access please ! :)

**Comment by bdougie** [comment]
Thanks for joining me last night everyone. I have submitted all your handles to our Actions PM to accelerate your Actions access. I look forward to seeing what you build!

I mentioned I am available to [meet for coffee](https://calendly.com/bdougie/coffee-w-bdougie) as well. (due to travel, I have limited availability).

See you on the internet 👋🏾
